### ISSUE TITLE
Issue with MSE 

### ISSUE THREAD

**Issue by matiasmachado** [Kuhlman-Lab/ThermoMPNN#14]
Hi!

The Colab implementation of ThermoMPNN fails to run if MSE residue is present in the structure...

I found that renaming MSE to MET in the PDB is enough to make it work...

Perhaps some simple code could be added to account for this residue commonly found in X-ray structures.

Best

**Comment by hdieckhaus** [comment]
Hi, thanks for identifying this issue! I am surprised this is happening, since the ThermoMPNN PDB parser has some code to handle MSE residues. However, it looks like this was only catching residues labeled as HETATM, so I added a few lines to catch residues labeled as ATOM entries but identified as MSE or SEC residues.

Please let me know if this resolves your issue. Otherwise, if you could send me the offending PDB, I can try to troubleshoot this particular case. Thanks!
