### ISSUE TITLE
Residue index starts at 0 for heatmap (and csv output)

### ISSUE THREAD

**Issue by DantonIvanochko** [Kuhlman-Lab/ThermoMPNN#19]
Hi ThermoMPNN team!

Thanks for providing this excellent tool available on Github and Colab. The Colab implementation produces a very nice heatmap of the output results and I have repurposed this code (below) as a function for my local build.

It appears that the residue index for the version on Github does not retain the original PDB residue index and instead reverts to starting at zero. Is there a way to run the custom_inference.py script and retain the input PDB's residue index? Additionally, is there functionality to indicate chain breaks?

Thanks again for providing this powerful tool to the research community!

thermoMPNN_heatmap.py script for anyone interested:

```
import argparse
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

def main():
	alphabet = 'ACDEFGHIKLMNPQRSTVWY'
	df = pd.read_csv(args.input_csv)
	positions = df['position'].unique()
	arr = np.zeros((positions.size, len(alphabet)), dtype=float)

	for p_idx, p in enumerate(positions):
		for a_idx, a in enumerate(alphabet):
			arr[p_idx, a_idx] = float(df.loc[(df['position'] == p) & (df['mutation'] == a)]['ddG_pred'].iloc[0])

	sns.set()
	sns.set(rc={"figure.figsize": (positions.size // 4, 5)})
	g = sns.heatmap(data=arr.T, cmap='RdBu_r', center=0, robust=True,
            xticklabels=positions, yticklabels=alphabet,
            vmin=-3, vmax=3, linewidth=0.5, cbar_kws={'label': 'ddG (kcal/mol)'})
	g.set(xlabel='Position', ylabel='Amino Acid', title='SSM Thermostability Profile');
	plt.yticks(rotation=0, ha='right');
	plt.savefig(args.output_png, format='png', dpi=300)


if __name__ == "__main__":

	parser = argparse.ArgumentParser()
	parser.add_argument("--input_csv", type=str, required=True, help="Input .csv file from thermoMPNN")
	parser.add_argument("--output_png", type=str, required=True, help="Output png file for heatmap")
	args = parser.parse_args()

	main()
```

**Comment by hdieckhaus** [comment]
hi @DantonIvanochko ,

As you might expect, ThermoMPNN inference uses the "absolute" residue numbering to identify which position(s) to mutate, but the PDB parsing function we are using (`alt_parse_PDB`), should return a list of residue indices for each PDB (called `resn_list` in the data dictionary). You should be able to map the "absolute" residue numbering back to the true residue indices using this list, since it should be a one-to-one mapping (with extra spots for any gaps in the structure).

So if you want to get the "true" PDB numbering for the 43rd "absolute" position, you can do
`true_pos = pdb['resn_list'][43]`

You can collect this for every mutation in a similar fashion.

ThermoMPNN is designed to run on monomers, but if you have multiple chains, you may still be able to extract the positional information, you just need to figure out what _order_ the chains are read in. In the PDB data dict, every chain will have a `seq_chain_X`, where X is the chain ID, and these are concatenated into `seq`, which is the total sequence. So to get the absolute chain/position of a specific residue, you'll have to add up the "offset" of any previous chains and then add your "absolute" numbering to it.

For example:
```
chainID = B
key_chain = f'seq_chain_{chainID}'

seq_keys = [k for k in pdb.keys() if k.startswith('seq_chain_')]

offset = 0
for sk in seq_keys:
    if sk == key_chain:
        break
    else:
        offset += len(pdb[sk])

true_pos = pdb['resn_list'][offset + 43]
```

I understand this is not a great system, and it is definitely something we are looking at streamlining for future releases, but this is where we are at for now. Hope this helps!
