### ISSUE TITLE
The fireprot csv in data_all  

### ISSUE THREAD

**Issue by xiaobingbuhuitou** [Kuhlman-Lab/ThermoMPNN#20]
Hello, The FireProt dataset csv in the 'data_all' folder does not match the description in the article. Could you please update it? Thanks.☺

**Comment by hdieckhaus** [comment]
Hi @xiaobingbuhuitou,

Thank you for your interest in ThermoMPNN and for letting us know about this discrepancy. I have gone ahead and updated the Fireprot dataset csvs in the data_all folder to match the article descriptions. These should contain the following number of unique proteins: 57/15/28/89 proteins in the train/val/test/homologue-free splits, respectively.

Note there may be some small discrepancies in the total number of mutations in the train/val/test sets (homologue-free should match the paper), as we have since done some further curation and found some hidden duplicate mutations that needed to be removed. The results should be quite similar.

Let me know if you have any further questions or issues.
