### ISSUE TITLE
Is prediction taking into account other chains?

### ISSUE THREAD

**Issue by gezmi** [Kuhlman-Lab/ThermoMPNN#3]
Hi,

Thanks for this fine-tuning, very interesting. I am wondering if during predictions, does it take into account the context? I understand that it was trained on monomers, still I have a couple of examples that I would like to run it on for comparing with exeperimental data.

Thank you!

**Comment by hdieckhaus** [comment]
Hello!

Thank you for your interest in ThermoMPNN! The short answer is yes, but it depends which inference function you use.

Long answer: ThermoMPNN uses the ProteinMPNN input PDB parser, which can parse multiple chains just fine, and the actual model should be able to use all of the chains during inference. However, you have to tell this parser which chain(s) to use, and some of the ThermoMPNN inference functions only load a single chain (since we haven't validated it on oligomers), meaning even if there are multiple chains in the file, they may be ignored.

The **ThermoMPNN Colab notebook** definitely doesn't use the other chains. Even if there are multiple chains in the file, it will only use the one you specify, and if you list multiple chains, it will throw an error. If you fail to specify a chain, it will choose the first one in the file. If you _really_ want to use this instead of the python interface, you can get around this by simply renumbering the PDB so that all the residues are in one giant "chain", which should work but will be annoying to parse the outputs since they will have new numbering.

The python interface is more permissive and easier to modify. For example, the **custom_inference.py** script should use all the chains in the file. You can either specify several chains or simply leave this argument out and it will automatically use all the chains.

example:
```
# option 1
python custom_inference.py --pdb example.pdb --chain A B --model_path ../models/thermoMPNN_default.pt

# option 2
python custom_inference.py --pdb example.pdb --model_path ../models/thermoMPNN_default.pt

```

If you want to use the large-scale inference capabilities, this requires setting up a PyTorch _Dataset_ object (see **datasets.py** for examples). As long as you tell the ProteinMPNN PDB parser to use all the chains, this should also work, but is more hassle to set up. If you want to see how to do this, you can find the _parse_PDB_ function in **protein_mpnn_utils.py** (the key argument is _input_chain_list_).

Hope this helps!

**Comment by hdieckhaus** [comment]
Hi Julia, 

Just wanted to let you know that the ThermoMPNN Colab notebook has been updated to enable multi-chain predictions. This feature has not been experimentally validated and may lead to parsing errors, but it is there if you want to try it. 

You can find this in Step 5: Run ThermoMPNN under "Enable multi-chain inference?". Check the box to enable it to use all chains during inference. I am closing this issue for now, reopen if needed.
