### ISSUE TITLE
PDBs

### ISSUE THREAD

**Issue by twidatalla** [Kuhlman-Lab/ThermoMPNN#7]
Hello, I am curious what PDBs were used for training on the megascale dataset and where one could find them? Was it just the alphafold models they included in their zenodo?

**Comment by hdieckhaus** [comment]
Hello! 

Yes, you are correct. We used the PDBs included in the [Zenodo repository](https://zenodo.org/record/7401275) of the Megascale dataset. 

These are a combination of AlphaFold models (for the natural proteins) and trRosetta/Rosetta models (for the de novo proteins) - you can tell which is which by checking the b-factor (pLDDT) columns. My understanding is that they provide AlphaFold models because in many cases the proteins are truncated or slightly modified for expression or to fit their assay format, so the PDB structures have slightly different sequences. We have found the model works well so far when predicting on either experimental (x-ray) structures or reasonably high-confidence (pLDDT > 0.60) AlphaFold/Rosetta models.

Hope this helps!
